'use client';

import Button from '@/components/ui/Button';
import Card from '@/components/ui/Card';
import { ExternalLink, ArrowRight } from 'lucide-react';
import Link from 'next/link';
import { getProfileArtwork } from '@/lib/marketing-images';

const JobReadyPortfoliosSection = ({ intro, portfolios = [] as any[] }: { intro?: { title?: string; description?: string; ctaLabel?: string; ctaHref?: string }; portfolios?: any[] }) => {
  const rows = portfolios.length ? portfolios : [{ id: 1, name: 'NISHU KUMAR', role: 'AI Engineer', href: '/portfolio/1', skills: [{ icon: 'PY', count: 2 }, { icon: 'AI', count: 1 }, { icon: 'ML', count: 3 }] }, { id: 2, name: 'Sreerag CR', role: 'Data Engineer', href: '/portfolio/2', skills: [{ icon: 'BI', count: 1 }, { icon: 'ETL', count: 2 }, { icon: 'CL', count: 1 }, { icon: 'QA', count: 1 }] }, { id: 3, name: 'Rajyvardhan Singh Parmar', role: 'Data Analyst', href: '/portfolio/3', skills: [{ icon: 'DA', count: 1 }, { icon: 'BI', count: 7 }, { icon: 'KR', count: 2 }, { icon: 'PM', count: 1 }] }];
  return <section className="px-4 py-16 bg-gradient-to-b from-white to-secondary-lighter dark:from-slate-900 dark:to-slate-950"><div className="max-w-7xl mx-auto"><div className="text-center mb-10"><h2 className="mb-3 text-3xl font-bold text-slate-950 dark:text-white">{intro?.title || 'Job-Ready Portfolios'}</h2><p className="mx-auto max-w-2xl text-slate-600 dark:text-slate-300">{intro?.description || 'See how our bootcamp learners use the Portfolio Website feature to showcase their skills.'}</p></div><div className="grid grid-cols-1 md:grid-cols-3 gap-6">{rows.map((portfolio) => <Card key={portfolio.id} className="p-6 transition-shadow hover:shadow-lg"><div className="flex items-start gap-4 mb-4"><img src={getProfileArtwork(portfolio.name)} alt={portfolio.name} className="h-16 w-16 rounded-full object-cover object-center shadow-lg shadow-primary-500/20" /><div><h3 className="text-lg font-bold text-slate-950 dark:text-white">{portfolio.name}</h3><p className="font-medium text-primary-600 dark:text-primary-300">{portfolio.role}</p></div></div><div className="flex gap-3 mb-4 flex-wrap">{(portfolio.skills || []).map((skill: any, index: number) => <div key={index} className="flex items-center gap-1 rounded-full bg-slate-100 px-3 py-1 dark:bg-slate-800"><span className="text-xs font-semibold text-slate-700 dark:text-slate-200">{skill.icon}</span><span className="text-sm font-medium text-slate-700 dark:text-slate-200">{skill.count}</span></div>)}</div><Link href={portfolio.href || `/portfolio/${portfolio.id}`}><Button variant="link" className="gap-1 p-0 h-auto text-primary-600 dark:text-primary-300">See Portfolio <ExternalLink className="w-4 h-4" /></Button></Link></Card>)}</div><div className="flex items-center justify-between mt-8"><Link href={intro?.ctaHref || '/portfolio'}><Button variant="outline" className="gap-2">{intro?.ctaLabel || 'Explore All Portfolios'} <ArrowRight className="w-4 h-4" /></Button></Link><div className="flex gap-2"><Button variant="outline" size="icon">Left</Button><Button variant="outline" size="icon">Right</Button></div></div></div></section>;
};

export default JobReadyPortfoliosSection;
