export const MOCK_COURSE_REVIEWS = [
  {
    reviewerName: 'Rabin Anto',
    reviewerAvatar: '/images/edvo-official-logo-v10.png',
    reviewerRole: 'Data Scientist',
    courseName: 'Data Analytics Bootcamp',
    courseSlug: '',
    category: 'Data Analytics',
    rating: 5,
    comment: 'Before enrolling in the course, my computer skills were extremely basic. The step-by-step projects and mentor support helped me grow into a confident data professional.',
    helpful: 24,
    externalUrl: 'https://www.linkedin.com/',
    sourceLabel: 'LinkedIn Review',
    status: 'active',
    order: 1,
  },
  {
    reviewerName: 'Omkar Prakash Gosavi',
    reviewerAvatar: '/images/edvo-official-logo-v10.png',
    reviewerRole: 'BI Analyst',
    courseName: 'Business Intelligence Bootcamp',
    courseSlug: '',
    category: 'Business Intelligence',
    rating: 5,
    comment: 'I am amazed with the contents that are included in this bootcamp. The roadmap was practical, the assignments felt real, and the sessions stayed focused on outcomes.',
    helpful: 18,
    externalUrl: 'https://www.linkedin.com/',
    sourceLabel: 'LinkedIn Review',
    status: 'active',
    order: 2,
  },
  {
    reviewerName: 'Bhikadiya Pratik',
    reviewerAvatar: '/images/edvo-official-logo-v10.png',
    reviewerRole: 'BI Reporting Analyst - III',
    courseName: 'Power BI and SQL Career Track',
    courseSlug: '',
    category: 'Power BI',
    rating: 5,
    comment: 'The practical approach and real-world projects helped me transition smoothly into my new role. The mentorship was exceptional and interview-focused.',
    helpful: 21,
    externalUrl: 'https://www.linkedin.com/',
    sourceLabel: 'LinkedIn Review',
    status: 'active',
    order: 3,
  },
];
