export const DEFAULT_HOME_CONTENT = {
  key: 'home',
  heroSlides: [
    {
      eyebrow: 'LIVE COHORT STARTED ON 7TH MARCH',
      title: 'AI Engineering Bootcamp',
      accent: 'Go from Software Engineer to AI Engineer in 75 Days',
      description: 'A project-first roadmap covering orchestration, agents, deployment, and real production-style workflows.',
      chips: ['BUILD', 'ORCHESTRATE', 'DISTRIBUTE'],
      primaryCta: { label: 'Explore Bootcamp', href: '/bootcamps' },
      secondaryCta: { label: 'Watch Demo', href: '/about' },
      note: 'Enrollments open until 13th March, 2026',
      panelTitle: 'Recordings Available',
      panelBody: 'Live sessions, guided build-alongs, mock interviews, and mentor checkpoints in one flagship cohort.',
      theme: { shell: 'from-[#eff6ff] via-white to-[#f8fafc] dark:from-[#0d1630] dark:via-[#131d40] dark:to-[#081024]', glow: 'from-blue-500/20 via-orange-500/10 to-transparent dark:from-blue-500/15 dark:via-orange-500/10', accent: 'text-orange-600 dark:text-orange-400' },
    },
    {
      eyebrow: 'FLAGSHIP DATA ANALYTICS TRACK',
      title: 'Data Analytics Career Accelerator',
      accent: 'Master Excel, SQL, Power BI, Python, and stakeholder storytelling',
      description: 'Everything needed to move from confusion to dashboard-ready execution with portfolio projects that feel interview-ready.',
      chips: ['ANALYZE', 'VISUALIZE', 'PRESENT'],
      primaryCta: { label: 'View Analytics Track', href: '/courses' },
      secondaryCta: { label: 'See Outcomes', href: '/alumni' },
      note: 'Built for beginners, career switchers, and working professionals',
      panelTitle: 'Project + Placement Focused',
      panelBody: 'Structured modules, guided capstones, resume proof, and review loops that keep learners shipping real work.',
      theme: { shell: 'from-[#f0f9ff] via-[#f8fafc] to-[#eff6ff] dark:from-[#0b1b3d] dark:via-[#10234a] dark:to-[#0a1532]', glow: 'from-blue-400/20 via-primary-500/10 to-transparent dark:from-blue-500/20 dark:via-primary-500/10', accent: 'text-primary-600 dark:text-primary-400' },
    },
    {
      eyebrow: 'COMMUNITY + CAREER MOMENTUM',
      title: 'Learn With Momentum, Not Guesswork',
      accent: 'Courses, challenges, mentors, and hiring support inside one focused ecosystem',
      description: 'Stop stitching together random tutorials. Follow one intentional path that moves you from skill building to visible outcomes.',
      chips: ['LEARN', 'BUILD', 'GET HIRED'],
      primaryCta: { label: 'Explore Courses', href: '/courses' },
      secondaryCta: { label: 'Browse Jobs', href: '/jobs' },
      note: 'Trusted by learners leveling up across analytics, AI, and software tracks',
      panelTitle: 'One Product, End to End',
      panelBody: 'From concept videos to project reviews and job-facing assets, the learner journey stays connected from start to finish.',
      theme: { shell: 'from-[#faf5ff] via-white to-[#f0f9ff] dark:from-[#111129] dark:via-[#151c3d] dark:to-[#0c152e]', glow: 'from-orange-500/10 via-blue-500/10 to-transparent dark:from-orange-500/10 dark:via-blue-500/10', accent: 'text-orange-600 dark:text-orange-400' },
    },
  ],
  socialStats: [
    { icon: 'Youtube', value: '1.4M+', label: 'YouTube Subscribers', color: 'text-red-500' },
    { icon: 'Users', value: '667K+', label: 'Enrolled Learners', color: 'text-blue-400' },
    { icon: 'GraduationCap', value: '76K+', label: 'Paid Learners', color: 'text-lime-400' },
    { icon: 'Star', value: '6000+', label: '5 star Reviews', color: 'text-yellow-400' },
  ],
  features: [
    { icon: 'Zap', title: 'Interactive Learning', description: 'Engage with hands-on projects, quizzes, and real-world challenges that reinforce your learning.', color: 'from-accent-500 to-accent-600' },
    { icon: 'Globe', title: 'Global Community', description: 'Join learners from 190+ countries. Collaborate, share knowledge, and grow together.', color: 'from-primary-500 to-primary-700' },
    { icon: 'Award', title: 'Industry Certificates', description: 'Earn recognized certificates upon completion to boost your career prospects.', color: 'from-primary-600 to-accent-500' },
    { icon: 'CheckCircle', title: 'Career Support', description: 'Get personalized career guidance, resume reviews, and interview preparation.', color: 'from-green-500 to-emerald-500' },
  ],
  careerTransformations: [
    { name: 'Kishan Singh', beforeRole: 'Database Administrator', afterRole: 'Data Analyst', company: 'From IT' },
    { name: 'Rohan Singh', beforeRole: 'Software Engineer', afterRole: 'AI Software Developer', company: 'From IT' },
    { name: 'Suchorita Das', beforeRole: 'Fresher', afterRole: 'Customer Success and MIS Reporting Executive', company: 'From Non-IT' },
  ],
  instructorsIntro: {
    badge: 'Our Team',
    title: 'Learn from AI & Data Experts with Real Industry Experience',
    accent: 'with Real Industry Experience',
    description: 'Industry experience meets the art of teaching, making complex concepts feel simple.',
  },
  cinematicSection: {
    badge: '4K Cinematic',
    title: 'Learning that feels like Entertainment.',
    accent: 'Entertainment.',
    description: 'We ditched grainy Zoom recordings for cinematic production. High-fidelity visuals, storytelling-driven edits, and immersive examples. You will not just study data, you will binge-watch it.',
    buttonLabel: 'Watch a Sample Lecture',
    previewEmoji: 'Movie',
    previewTitle: 'EDVO',
    previewSubtitle: 'Learn like you are watching a movie',
  },
  portfoliosIntro: {
    title: 'Job-Ready Portfolios',
    description: 'See how our bootcamp learners use the Portfolio Website feature to showcase their skills.',
    ctaLabel: 'Explore All Portfolios',
    ctaHref: '/portfolio',
  },
  portfolios: [
    { id: 1, name: 'NISHU KUMAR', role: 'AI Engineer', href: '/portfolio/1', skills: [{ icon: 'PY', count: 2 }, { icon: 'AI', count: 1 }, { icon: 'ML', count: 3 }] },
    { id: 2, name: 'Sreerag CR', role: 'Data Engineer', href: '/portfolio/2', skills: [{ icon: 'BI', count: 1 }, { icon: 'ETL', count: 2 }, { icon: 'CL', count: 1 }, { icon: 'QA', count: 1 }] },
    { id: 3, name: 'Rajyvardhan Singh Parmar', role: 'Data Analyst', href: '/portfolio/3', skills: [{ icon: 'DA', count: 1 }, { icon: 'BI', count: 7 }, { icon: 'KR', count: 2 }, { icon: 'PM', count: 1 }] },
  ],
  youtubeSection: {
    title: 'Watch on Youtube',
    subscribers: '1.4M+ Subscribers',
    channelUrl: 'https://youtube.com/@edvo',
    buttonLabel: 'Open Channel',
  },
  youtubeVideos: [
    { id: 1, title: 'AI Engineer Roadmap | How I\'d Learn AI in 2026', views: '700K+', duration: '45:30' },
    { id: 2, title: 'Python Pandas | Introduction & Installation', views: '700K+', duration: '32:15' },
    { id: 3, title: 'How to become an expert in Python', views: '700K+', duration: '28:45' },
  ],
  hiringPartnersSection: {
    title: 'Our Alumni Work at Top Companies',
    description: 'Join 76K+ learners who\'ve transformed their careers',
    buttonLabel: 'View All Success Stories',
    buttonHref: '/alumni-achievements',
  },
  hiringPartners: [
    { name: 'INTEG', logo: '/images/partners/integ.png' },
    { name: 'IQVIA', logo: '/images/partners/iqvia.png' },
    { name: 'Numerator', logo: '/images/partners/numerator.png' },
    { name: 'OLA ELECTRIC', logo: '/images/partners/ola.png' },
    { name: 'ORACLE', logo: '/images/partners/oracle.png' },
    { name: 'P&G', logo: '/images/partners/pg.png' },
    { name: 'SBFC', logo: '/images/partners/sbfc.png' },
    { name: 'TCS', logo: '/images/partners/tcs.png' },
    { name: 'THE MEDIA ANT', logo: '/images/partners/media-ant.png' },
  ],
  testimonialsIntro: {
    badge: 'Student Voices',
    title: 'Real Stories, Real Growth',
    accent: 'Real Growth',
    description: 'Discover how our learners transformed their careers with the right guidance and skills.',
  },
  homeTestimonials: [
    { id: 1, name: 'Rabin Anto', role: 'Data Scientist', badge: 'Landed A Job', quote: 'Before enrolling in the course, my computer skills were extremely basic. It took me five months to complete the course, and after that, I began my job search. I dedicated myself to working on Power BI projects as if it were my...', linkedin: '#', video: false },
    { id: 2, name: 'Omkar Prakash Gosavi', role: 'BI Analyst', quote: 'I am amazed with the contents that are included in this bootcamp. The effort that have been taken to help so many students and professionals to grow in the field of Data Science and Data can be seen through the initial...', linkedin: '#', video: false },
    { id: 3, name: 'Bhikadiya Pratik', role: 'BI Reporting Analyst - III', badge: 'Landed A Job', quote: 'The practical approach and real-world projects helped me transition smoothly into my new role. The mentorship was exceptional!', linkedin: '#', video: true },
  ],
  hireTalentHero: {
    badge: 'For HRs & Hiring Managers',
    title: 'Hire The Best Data Professionals at',
    accent: 'zero cost.',
    description: 'Skip CV screening, interview rounds, and save 2X time by hiring vetted Data Analysts and Engineers from our talent pool.',
    primaryLabel: 'Become a Partner',
    primaryHref: '/hire-talent/apply',
    trustNote: 'Trusted by 350+ Industry Leaders',
    backgroundImage: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=80&w=2000',
  },
  hireTalentTestimonials: [
    {
      quote: 'EDVO demonstrated a deep understanding of our requirements and delivered candidates who not only possessed the technical skills but also fit seamlessly into our company culture.',
      author: 'Bharath Kumar',
      role: 'Head - BI & Analytics, SBFC',
      image: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=200',
    },
    {
      quote: 'As a hiring manager who frequently partners with EDVO, I have been consistently impressed with the caliber of candidates. Their focus on practical, project-based learning is exactly what we need.',
      author: 'Subham Singh',
      role: 'Business Analyst, The Media Ant',
      image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=200',
    },
  ],
  hireTalentCta: {
    title: 'Ready to skip the hiring hustle?',
    description: 'Partner with us today and get access to the top 1% of our vetted data talent. No hidden fees, just great talent.',
    primaryLabel: 'Partner With Us',
    primaryHref: '/hire-talent/apply',
    secondaryLabel: 'See Success Stories',
    secondaryHref: '/testimonials',
  },  ctaSection: {
    title: 'Ready to Start Your Journey?',
    description: 'Join thousands of students who are already learning and growing with EDVO. Start your free trial today!',
    primaryLabel: 'Get Started Free',
    primaryHref: '/auth/register',
    secondaryLabel: 'View Pricing',
    secondaryHref: '/pricing',
  },
};

